
# 1. 가볍고 보안성이 높은 node 20 alpine 이미지 사용
FROM node:20-alpine

# 2. 컨테이너 내부 작업 디렉토리 생성
WORKDIR /usr/src/app

# 3. 의존성 설치를 위해 package.json 우선 복사 (Docker Cache 활용)
COPY package*.json ./

# 4. 패키지 설치
RUN npm install

# 5. 소스코드 전체 복사
COPY . .

# 6. NestJS 기본 포트 노출
EXPOSE 3000

# 7. 개발용 핫 리로딩 명령어 실행
CMD ["npm", "run", "start:dev"]